language: objective-c
install: echo
script:
  - xcodebuild -project ImageUploader.xcodeproj -sdk iphonesimulator7.0 -configuration Debug -destination 'platform=iOS Simulator,OS=7.0,name=iPhone Retina (4-inch)' -scheme 'ImageUploader' test